-- GenreGen, Version 1.1
-- Written by Vyhd (http://boxorroxors.net/)

-- Licensed under Creative Commons Attribution-Share Alike 3.0 Unported
-- ( http://creativecommons.org/licenses/by-sa/3.0/ )
-- All I ask is that you keep this notice intact. :)

-- Shoutouts to Konami for making an awesome game and filling it with
-- ridiculous genres. Every single string here is straight from IIDX. :>

GenreGen = {}

GenreGen.Defs =
{
	-- the main genre. may be listed on its own.
	Main =
	{
		"2Step",
		"Africa",
		"Ambient",
		"America",
		"Baroque",
		"Beat",
		"Bossa",
		"Breaks", 
		"Breakbeat",
		"Cabaret",
		"Celtrance",
		"Chanson",
		"Choir",
		"Concerto",
		"Crossover",
		"Cuddlecore",
		"Dance",
		"Dirge",
		"Disco",
		"Drum & Bass",
		"Electro",
		"Electrock",
		"Electronic",
		"Extreme",
		"France",
		"Full On",
		"Funk",
		"Fusion",
		"Gabba",
		"Gabber",
		"Handz Up",
		"Hardcore",
		"House",
		"Instrumental",
		"Japan", 
		"J-Pop",
		"J-Pop+",
		"J-Rock",
		"Jungle",
		"K-Groove",
		"Latin Horns",
		"Lounge",
		"Minimal",
		"Mixture",
		"Nu-NRG",
		"Opera",
		"Opus",
		"Oratorio",
		"Orchestral",
		"Paradise",
		"Piano'n'Bass",
		"Poetry",
		"Pop",
		"Pops",
		"Progressive",
		"Psychedelic",
		"Renaissance",
		"Requiem",
		"Rock",
		"Salsa",
		"Schranz",
		"Slowcore",
		"Softcore",
		"Sonata",
		"Soul",
		"Sound",
		"Spiritual",
		"Swing",
		"Techno",
		"Tec-Drum'n'Bass",
		"Tek",
		"Trance",
		"Waltz",
	};

	-- a secondary descriptor, which is likely be shown.
	Desc1 =
	{
		"Asian",
		"Beat",
		"BigBeat",
		"Broken",
		"Buchiage",
		"Click",
		"Club",
		"Country",
		"Cute",
		"Cyber",
		"Cyborg",
		"Death",
		"Deceptive",
		"Dutch",
		"Epic",
		"Erhu",
		"Electric",
		"Esoteric",
		"Ethno",
		"Euro",
		"Freeform",
		"Garage",
		"Goa",
		"Gothic",
		"Happy",
		"Hard",
		"Hindu",
		"Hip",
		"Italo",
		"J-Happy",
		"Lovers",
		"Medieval",
		"Millennium",
		"Natural",
		"Noise",
		"Nostalish",
		"Nustyle",
		"Power",
		"Punk",
		"Ragga",
		"Reckless",
		"Rococo",
		"Sadistic",
		"Scouse",
		"Spanish",
		"Speed",
		"Sublime",
		"SuperNOVA",
		"Tribal",
		"Turkish",
		"World",
	};

	-- tertiary descriptor. shouldn't appear often.
	Desc2 =
	{
		"Alternative",
		"Dramatic",
		"High Speed",
		"Hyper",
		"Lovely",
		"Oldskool",
		"Nu",
		"Super",
		"Synthetic",
	};
};